# Generated by Django 2.0.13 on 2019-05-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190511_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified_email',
            field=models.BooleanField(default=False),
        ),
    ]
