version: "3.7"

services:
  backend:
    container_name: starnavi-backend
    image: zoxon470/starnavi-backend:latest
    command: ./start.sh
    env_file:
      - django/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  bot:
    container_name: starnavi-bot
    image: zoxon470/starnavi-bot:latest
    command: ./start.sh
    env_file:
      - bot/.env
    depends_on:
      - backend

  rq:
    image: zoxon470/starnavi-backend:latest
    command: python manage.py rqworker default
    env_file:
      - django/.env
    depends_on:
      - db
      - redis

  redis:
    container_name: starnavi-redis
    image: redis:5.0.4-alpine
    restart: on-failure
    ports:
      - "6379"

  db:
    container_name: starnavi-db
    image: postgres:10.1-alpine
    restart: on-failure
    env_file:
      - django/.env
    volumes:
      - pgdata:${PGDATA:-/var/lib/postgresql/data}
    ports:
      - "5432"

volumes:
    pgdata:
